routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FileUploadController;
use App\Http\Controllers\IframeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Models\Quote;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $settings = [];
    return view('index',compact("settings"));
});

Route::get("/viewer",[IframeController::class, "view"])->name("viewer");

Route::get('/', [AuthController::class,'login']);

Route::get('/profile', [ProfileController::class,'profile']);

Route::post('/profile', [ProfileController::class,'profilePost']);

Route::get('/new-user', [ProfileController::class,'newUser']);

Route::get('/staff', [ProfileController::class,'staff'])->name("staff.index");

//Route::get('/staff/{project_id}', [ProfileController::class,'staff'])->name("assign-project");

Route::post('/user-post', [ProfileController::class,'userPost']);

Route::post('/user-change-password', [ProfileController::class,'userChangePasswordPost']);

Route::get('/login', [AuthController::class,'login'])->name('login');
Route::get('/signup', [AuthController::class,'signup']);
Route::get('/forgot-password', [AuthController::class,'forgotPassword']);
Route::get('/password-reset', [AuthController::class,'passwordReset']);

Route::get('/logout', [AuthController::class,'logout']);

Route::post('/login', [AuthController::class,'loginPost']);

Route::get('/dashboard', [DashboardController::class,'dashboard']);

Route::get('/add-project', [ProjectController::class,'addProject'])->name("add-project");

Route::post('/store-project', [ProjectController::class,'storeProject'])->name("store-project");

Route::get('/project-detail/{id}', [ProjectController::class,'projectDetails'])->name("project-detail");

Route::get('/project/{id}', [DashboardController::class,'editProject'])->name("edit-project");

Route::post('/update-project/{id}', [DashboardController::class,'updateProject'])->name("update-project");

//Route::post('/upload-image', [ImageController::class, 'dropZone' ])->name('drag-drop');

Route::resource('/modules', ModuleController::class);

Route::get('/modules/documentation/{module_id}', [ModuleController::class, "moduleDocumentation"])->name("module-documentation");

Route::resource("/jobs", JobController::class);

Route::get("/jobs-dashboard", [JobController::class,"dashboard"])->name("jobs-dashboard");

//Route::post("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");
Route::get("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");

Route::resource('/tasks', TaskController::class);

Route::get('/document-task/{id}', [TaskController::class,"document"])->name("document-task");

Route::post('/document-task/{id}', [TaskController::class,"documentTask"])->name("task.document");

Route::post('/modules/assign-module', [ModuleController::class, 'assignModule'])->name('assign-module');

Route::get('uploads', [FileUploadController::class, 'fileUploads' ])->name('fileUploads');

//Route::get("/")

//Route::post('file-upload', [FileUploadController::class, 'dropzoneFileUpload' ])->name('dropzoneFileUpload');
Route::post('file-upload', [FileUploadController::class, 'uploadZips' ])->name('dropzoneFileUpload');

Route::get('/test', function (){
    return \App\Models\Task::with(['module' => function($module){
        return $module->with("user");
    }])->get();
});

Route::get('/html-assets/{directory}/{page}', function (\Illuminate\Http\Request $request) {
    if (!$request->hasValidSignature()) {
        abort(401);
    }
});

Route::get("/store-quotes", function(){
     $response = Http::get("https://type.fit/api/quotes");
//     return $response->collect();
     foreach ($response->collect() as $res){
         Quote::create([
             "text" => $res['text'],
             "author" => $res['author'],
         ]);
     }
});

resources/views/board/dashboard.blade.php
@extends('layouts.primary')

@section('content')

    <div class="container-fluid py-4">
        <div class="card mt-4">
            <div class="card-header pb-0 p-3">
                <div class="d-flex align-items-center">
                    <h6 class="mb-0">{{__('Jobs Dashboard')}}</h6>

                </div>
            </div>

            <div class="table-responsive">
                <table class="table align-items-center mb-0">
                    <thead>
                    <tr>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            {{__('Gig Name')}}
                        </th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                            {{__('Start Date')}}

                        </th>

                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">{{__('End Date')}}</th>

                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">{{__('Showed Interest')}}</th>

                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">{{__('Applied')}}</th>

                    </tr>
                    </thead>
                    <tbody>

                    @foreach($modules as $module)
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div class="avatar avatar-sm me-3 bg-gradient-dark border-radius-md p-2">
                                        <h6 class="text-white">{{$module->name['0']}}</h6>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-xs">{{$module->name}}</h6>

                                    </div>
                                </div>
                            </td>

                            <td class="align-middle text-center text-sm">
                                <span class="badge bg-gradient-success font-weight-bold">{{$module->start_date}}</span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <span class="badge bg-gradient-primary font-weight-bold">{{$module->end_date}}</span>
                            </td>

                            <td></td>
                            <td></td>

                        </tr>



                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection


@section('script')

    <script>
        "use strict"
        $(function () {
            $('.todo_checkbox').on('change',function () {
                let that = $(this);
                if(this.checked)
                {
                    $.post('/todos/change-status',{
                        id: that.attr('data-id'),
                        status: 'Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
                else{
                    $.post('/todos/change-status',{
                        id: that.attr('data-id'),
                        status: 'Not Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
            });
        });
    </script>
    <script>

        $(function () {
            $('.goal_checkbox').on('change',function () {
                let that = $(this);
                if(this.checked)
                {
                    $.post('/goals/change-status',{
                        id: that.attr('data-id'),
                        status: 'Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
                else{
                    $.post('/goals/change-status',{
                        id: that.attr('data-id'),
                        status: 'Not Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
            });
        });
    </script>


@endsection

resources/views/board/jobs.blade.php
@php
    $admin = Auth::user()->admin;
    $hasModules = !(sizeof($modules) < 1);
@endphp

@extends('layouts.primary')
@section('content')

    <style>
        .chip{
            width: auto;
            color: white;
            background-color: #2F3459;
            border-radius: 7px;
            margin-right: 5px;
            margin-top: 5px;

        }
    </style>

    <div class="page-header mb-4 border-radius-xl">
        <span class="mask bg-gradient-dark"></span>
        <div class="container">
            <div class="row">

                <div class="col-lg-6 my-auto">
                    <h5 class="text-white fadeIn2 fadeInBottom mt-4">
                        {{__($quote->text)}}
                    </h5>
                    <p class="text-white opacity-8 fadeIn3 fadeInBottom">{{__($quote->author)}} </p>
                </div>
            </div>
            @if($admin)
{{--                <a  href="{{$create_url}}" type="button" class="btn bg-gradient-light">{{__('Create Module')}}</a>--}}
            @endif
        </div>
    </div>


    <div class="container-fluid py-4">
        <section class="py-3">
            <div class="row">
                <div class="col-md-8 me-auto text-left">
                    <h5>{{__("Job Board")}}</h5>

                </div>
            </div>
            @if($hasModules)
                    <div class="row mt-lg-4 mt-2" >
                        @foreach($modules as $module)

                            <div class="col-lg-4 col-md-6 mb-4">
                                @if(Request::has("staff"))

                                    <div class="card card-blog" >
                                        @else
                                            <div class="card card-blog ">
                                                @endif
                                                <div class="card-body p-3">
                                                    <div class="d-flex">
                                                        <div class="avatar avatar-xl bg-gradient-dark border-radius-md p-2">
                                                            <h1 class="text-white">{{$module->name['0']}}</h1>
                                                        </div>
                                                        <div class="ms-3 my-auto">
                                                            <h6>{{$module->name}}</h6>
                                                        </div>
                                                    </div>

                                                    <p class="text-sm mt-3"> {{$module->summary}} </p>
                                                    <span class="badge bg-gradient-success font-weight-bold">{{$module->status}}</span>

                                                    @if($module->end_date < \Carbon\Carbon::now()->toDateString())
                                                        <span class="badge bg-gradient-danger font-weight-bold">
                                                Overdue
                                            </span>
                                                    @endif


                                                    <hr class="horizontal dark">
                                                    <div class="row">
                                                        <div class="col-6 ">
                                                            <h6 class="text-sm mb-0">{{$module->start_date}}</h6>
                                                            <p class="text-secondary text-sm font-weight-bold mb-0">{{__('Start date')}}</p>
                                                        </div>
                                                        <div class="col-6 text-end">
                                                            <h6 class="text-sm mb-0">{{$module->end_date}}</h6>
                                                            <p class="text-secondary text-sm font-weight-bold mb-0">{{__('Due date')}}</p>
                                                        </div>
                                                        <div class="btn-group">

                                                            @if(Request::has("staff"))

                                                                @if(\App\Models\UserModule::whereUserId(Request::query("staff"))->whereModuleId($module->id)->first())
                                                                    <a href="#"  type="button" class="btn bg-gradient-dark mt-3 unassign-module" data-id="{{$module->id}}">{{__('Assigned')}}</a>
                                                                @else
                                                                    <form action="{{route('assign-module')}}" method="POST">
                                                                        @csrf
                                                                        <input type="hidden" name="module_id" value="{{$module->id}}"/>
                                                                        <input type="hidden" name="user_id" value="{{Request::query('staff')}}"/>
                                                                        <button type="submit" class="btn bg-gradient-dark mt-3">{{__('Assign Module')}}</button>
                                                                    </form>
                                                                @endif
                                                            @else

                                                                <a href="{{route('jobs.show', $module->id)}}" type="button" class="btn bg-gradient-dark mt-3">{{__('View')}}</a>


                                                                <a href="" type="button" class="btn bg-gradient-secondary mt-3">
                                                                    {{__('SHOW INTEREST')}}
                                                                </a>

{{--                                                                <form method="POST" action="{{route('take-gig',$module->id) }}">--}}
                                                                    @csrf
                                                                @if(\App\Models\GigJob::applied($module->id))
                                                                    <a href="#"
                                                                @endif

                                                                <a href="{{route('take-gig',$module->id) }}"
{{--                                                                   onclick="event.preventDefault(); this.closest('form').submit();" --}}
                                                                   type="button" class="btn bg-gradient-primary mt-3">
                                                                    @if(\App\Models\GigJob::applied($module->id))

                                                                         {{__('APPLIED')}}
                                                                    @else
                                                                        {{__('TAKE GIG')}}
                                                                    @endif
                                                                </a>

{{--                                                                </form>--}}
                                                            @endif

                                                        </div>

                                                        <div class="row m-lg-3 ml-5">

                                                            @foreach($module->skills as $skill)
                                                                <div class="chip">
                                                                    {{$skill->skill->name}}
                                                                </div>
                                                            @endforeach
                                                        </div>

                                                        <div class="col-12 mt-3 ">

                                                            <div class="progress" style="height: 20px">
                                                                <div class="progress-bar" role="progressbar"
                                                                     style="width: {{\App\Models\Task::PointsPercentage($module->id)}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                                                                </div>

                                                            </div>

                                                            <p class="text-secondary text-sm font-weight-bold mb-0">{{__('Completed Status')}}</p>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>
                                    </div>
                                    @endforeach
                            @if($admin)
                                        <div class="col-lg-4 col-md-6 mb-4">
                                            <div class="card h-100">
                                                <div class="card-body d-flex flex-column justify-content-center text-center">
        {{--                                            <a href="{{$create_url}}">--}}
        {{--                                                <i class="fa fa-plus text-secondary mb-3"></i>--}}
        {{--                                                <h5 class=" text-secondary">{{__('New Module')}} </h5>--}}
        {{--                                            </a>--}}
                                                </div>
                                            </div>
                                        </div>
                                    @endif
                    </div>

            @else

                <h4 class="h4 text-center">NO JOBS FOR NOW!</h4>

            @endif

            </div>
        </section>

    </div>

@endsection

@section('script')
    <script>
        $(".unassign-module").on("click",function (){
            let id = $(this).data("id");
            let action = confirm("Are you sure you want to unconfirm?")
            if (action){
                alert("module-"+id);
            }
        })
    </script>
@endsection

resources/views/board/show.blade.php
@extends("layouts.primary")

@section("content")

<div class="container-fluid py-4">
    <div class="col-lg-9 mx-auto">
        <div class="card card-body ">
            <div class="page-header mb-4 border-radius-xl">
                <span class="mask bg-gradient-dark"></span>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 mt-3 mb-6 text-center my-auto">
{{--                            <h3 class="text-white">--}}
{{--                                {{$module->name}} Documentation--}}
{{--                            </h3>--}}
                            <h2 class="text-white fadeIn2 fadeInBottom mt-4">{{$module->name}}</h2>
                            <h5 class="text-white fadeIn2 fadeInBottom">{{$module->start_date}} - {{$module->end_date}}</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="text-center mt-4">
                <h4>Module Description</h4>
            </div>

            <div>
                <p class="pl-5">
                    {!! $module->description !!}
                </p>
            </div>

            @foreach($tasks as $task)

            <div class="text-center mt-4">
                <h6>{{$task->name}}</h6>
            </div>

            <div>
                <p class="pl-5">
                    {!! $task->description !!}
                </p>
            </div>
            @endforeach

        </div>
    </div>
</div>

@endsection