routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FileUploadController;
use App\Http\Controllers\IframeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Models\Quote;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $settings = [];
    return view('index',compact("settings"));
});

Route::get("/viewer",[IframeController::class, "view"])->name("viewer");

Route::get('/', [AuthController::class,'login']);

Route::get('/profile', [ProfileController::class,'profile']);

Route::post('/profile', [ProfileController::class,'profilePost']);

Route::get('/new-user', [ProfileController::class,'newUser']);

Route::get('/staff', [ProfileController::class,'staff'])->name("staff.index");

//Route::get('/staff/{project_id}', [ProfileController::class,'staff'])->name("assign-project");

Route::post('/user-post', [ProfileController::class,'userPost']);

Route::post('/user-change-password', [ProfileController::class,'userChangePasswordPost']);

Route::get('/login', [AuthController::class,'login'])->name('login');
Route::get('/signup', [AuthController::class,'signup']);
Route::get('/forgot-password', [AuthController::class,'forgotPassword']);
Route::get('/password-reset', [AuthController::class,'passwordReset']);

Route::get('/logout', [AuthController::class,'logout']);

Route::post('/login', [AuthController::class,'loginPost']);

Route::get('/dashboard', [DashboardController::class,'dashboard']);

Route::get('/add-project', [ProjectController::class,'addProject'])->name("add-project");

Route::post('/store-project', [ProjectController::class,'storeProject'])->name("store-project");

Route::get('/project-detail/{id}', [ProjectController::class,'projectDetails'])->name("project-detail");

Route::get('/project/{id}', [DashboardController::class,'editProject'])->name("edit-project");

Route::post('/update-project/{id}', [DashboardController::class,'updateProject'])->name("update-project");

//Route::post('/upload-image', [ImageController::class, 'dropZone' ])->name('drag-drop');

Route::resource('/modules', ModuleController::class);

Route::get('/modules/documentation/{module_id}', [ModuleController::class, "moduleDocumentation"])->name("module-documentation");

Route::resource("/jobs", JobController::class);

Route::get("/jobs-dashboard", [JobController::class,"dashboard"])->name("jobs-dashboard");

//Route::post("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");
Route::get("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");

Route::resource('/tasks', TaskController::class);

Route::get('/document-task/{id}', [TaskController::class,"document"])->name("document-task");

Route::post('/document-task/{id}', [TaskController::class,"documentTask"])->name("task.document");

Route::post('/modules/assign-module', [ModuleController::class, 'assignModule'])->name('assign-module');

Route::get('uploads', [FileUploadController::class, 'fileUploads' ])->name('fileUploads');

//Route::get("/")

//Route::post('file-upload', [FileUploadController::class, 'dropzoneFileUpload' ])->name('dropzoneFileUpload');
Route::post('file-upload', [FileUploadController::class, 'uploadZips' ])->name('dropzoneFileUpload');

Route::get('/test', function (){
    return \App\Models\Task::with(['module' => function($module){
        return $module->with("user");
    }])->get();
});

Route::get('/html-assets/{directory}/{page}', function (\Illuminate\Http\Request $request) {
    if (!$request->hasValidSignature()) {
        abort(401);
    }
});

Route::get("/store-quotes", function(){
     $response = Http::get("https://type.fit/api/quotes");
//     return $response->collect();
     foreach ($response->collect() as $res){
         Quote::create([
             "text" => $res['text'],
             "author" => $res['author'],
         ]);
     }
});

resources/views/add-project-deprecated.blade.php
@extends('layouts.primary')

@section('head')
{{--    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">--}}
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/dropzone.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"></script>

@endsection

@section('content')

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    {{ __('  Add New Project') }}

                    <a href="/dashboard" type="submit" class="btn bg-gradient-secondary float-end">{{ __('Go to Projects') }}</a>
                </div>

                <div class="card-body">
                    <form action="{{route('store-project')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @if ($errors->any())
                            <div class="alert alert-danger" style="color: white">
                                <ul class="list-unstyled">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Name') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="name" type="text" id="title" value="{{old('name')}}">
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1">{{ __('Description') }}</label><span class="text-danger">*</span>
                            <textarea class="form-control" name="description" id="description" rows="3">  </textarea>
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Repository Url') }}</label><span class="text-danger">*</span>
                            <select class="form-control" name="repository_url">
                                <option>Select Project</option>
                                @foreach($repositories as $repository)
                                    <option value="{{$repository["links"]["clone"][0]["href"]}}">{{$repository["full_name"]}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Developer Guide') }}</label><span class="text-danger">*</span>
                            <br>
                            <span class="small"></span>
                            <input class="form-control"  name="asset_url" type="file" id="asset_url" value="{{old('asset_url')}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('User Guide Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="doc_base_url" type="file" id="doc_base_url" value="{{old('doc_base_url')}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Wireframe (Draw.io)') }}</label><span class="text-danger"> (if any) </span>
                            <input class="form-control"  name="wireframe_url" type="file" id="wireframe_url" value="{{old('wireframe_url')}}">
                        </div>


                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project API EndPoints Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="api_endpoints_url" type="text" id="doc_base_url" value="{{old('api_endpoints_url')}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Dev Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="dev_url" type="text" id="dev_url" value="{{old('dev_url')}}">
                        </div>

                        <div class="form-group">
                            <label for="example-date-input" class="form-control-label">{{ __('Date') }}</label>
                            <input class="form-control" name="date" type="date" value="{{date('Y-m-d')}}" id="date">
                        </div>

                        <input type="hidden" name="id" value="">
                        <button type="submit" class="btn bg-gradient-secondary">{{ __('Save') }}</button>
                        <button type="button" class="btn bg-gradient-primary">{{ __('Close') }}</button>
                    </form>

                </div>

            </div>
        </div>


            <div class="col-md-6">
                <div class="card">
                    <div class="card-header p-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h6 class="mb-0">{{ __('Project list') }}</h6>
                            </div>

                        </div>
                        <hr class="horizontal dark mb-0">
                    </div>
                    <div class="card-body p-3 pt-0">
                        <ul class="list-group list-group-flush" data-toggle="checklist">
                            @foreach($projects as $project)
                                <li class="list-group-item border-0 flex-column align-items-start ps-0 py-0 mb-3">
                                    <div class="checklist-item checklist-item-primary ps-2 ms-3">
                                        <div class="d-flex align-items-center">


                                            <div class="form-check">
                                                <input class="form-check-input todo_checkbox" type="checkbox"
                                                       data-id=""
                                                >

                                            </div>
                                            <h6 class="mb-0 text-dark font-weight-bold text-sm">{{$project->name}}</h6>
                                            <div class="dropdown float-lg-end ms-auto pe-4">
                                                <a href="javascript:;" class="cursor-pointer" id="dropdownTable2" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="#"><i class="far fa-trash-alt me-2"></i>Delete</a>
                                                    <a class="btn btn-link text-dark px-3 mb-0" href="#"><i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Edit</a>
                                                </a>

                                            </div>
                                        </div>
                                        <div class="d-flex align-items-center ms-4 mt-3 ps-1">
                                            <div>
                                                <p class="text-xs mb-0 text-secondary font-weight-bold">Date</p>
                                                <span class="text-xs font-weight-bolder"></span>
                                            </div>

                                        </div>
                                    </div>
                                    <hr class="horizontal dark mt-4 mb-0">
                                </li>
                            @endforeach

                        </ul>
                    </div>
                </div>

            </div>
    </div>

{{--    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">--}}
{{--        <div class="modal-dialog modal-lg">--}}
{{--            <div class="modal-content">--}}
{{--                <div id="dropzone">--}}
{{--                    <form action="{{ route('dropzoneFileUpload') }}" class="dropzone" id="file-upload" enctype="multipart/form-data">--}}
{{--                        @csrf--}}
{{--                        <div class="dz-message">--}}
{{--                            Drag and Drop Single/Multiple Files Here<br>--}}
{{--                        </div>--}}
{{--                    </form>--}}
{{--                </div>--}}

{{--                <div class="container">--}}
{{--                <div class="form-group">--}}
{{--                    <form>--}}
{{--                        @csrf--}}
{{--                        <label for="example-text-input" class="form-control-label">{{ __('Upload') }}</label><span class="text-danger">*</span>--}}
{{--                        <input type="file" name="doc_base_url" id="doc_base_url" class="form-control" />--}}

{{--                        <button type="button" class="btn btn-success upload-file">Upload</button>--}}
{{--                    </form>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}


@endsection


@section('script')

    <script>

        $(".upload-file").on("click",function (){
            var input = document.querySelector('input[type="file"]')

            var data = new FormData()
            data.append('file', input.files[0])
            data.append('user', 'hubot')

            fetch("{{route('dropzoneFileUpload')}}", {
                method: 'POST',
                body: data
            })
        })

    </script>


    <script>
        "use strict";
        $(function () {


            flatpickr("#date", {

                dateFormat: "Y-m-d",
            });

        });




    </script>

    <script>
        tinymce.init({
            selector: '#description',


            plugins: 'table,code',


        });
    </script>
    <script>
        $(function () {
            $('.todo_checkbox').on('change',function () {
                let that = $(this);
                if(this.checked)
                {
                   $.post('/todos/change-status',{
                       id: that.attr('data-id'),
                       status: 'Completed',
                       _token: '{{csrf_token()}}',
                   });
                }
                else{
                    $.post('/todos/change-status',{
                        id: that.attr('data-id'),
                        status: 'Not Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
            });
        });
    </script>

    <script>
        $(".select-skills").select2({
            placeholder: 'Type skill name...',
            minimumInputLength: 3,
            theme: "classic",
            allowClear: true,
            ajax: {
                url: '/api/skills',
                dataType: 'json',
                data: function(params) {
                    return {
                        q: params.term
                    }
                },
                processResults: function (data, page) {
                    return {
                        results: data
                    };
                },
                cache: true
            }
        });

    </script>

    <script>
        const submitBtn = $("#submitBtn");

        function disableButton(){
            submitBtn.html("Uploading...");
            setTimeout(function (){
                submitBtn.prop("disabled",true);
            },500)
        }
    </script>



@endsection

resources/views/edit-project.blade.php
@extends('layouts.primary')
@section('content')



    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    {{ __('  Edit Project') }}

                    <a href="/dashboard" type="submit" class="btn bg-gradient-secondary float-end">{{ __('Go to Projects') }}</a>
                </div>

                <div class="card-body">
                    <form action="{{route('update-project',$project->id)}}" method="post">
                        @csrf
                        @if ($errors->any())
                            <div class="alert alert-danger" style="color: white">
                                <ul class="list-unstyled">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Name') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="name" type="text" id="title" value="{{$project->name}}">
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1">{{ __('Description') }}</label><span class="text-danger">*</span>
                            <textarea class="form-control" name="description" id="description" rows="3" > {{$project->description}} </textarea>
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Repository Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="repository_url" type="text" id="repository_url" value="{{$project->repository_url}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Asset Url(s)') }}</label><span class="text-danger">*</span>
                            <span class="small"> Separate urls with a comma(,)</span>
<!--                            <input class="form-control"  name="asset_url" type="text" id="asset_url">-->
                            <textarea class="form-control" name="asset_url">{{$project->asset_url}}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Doc Base Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="doc_base_url" type="text" id="doc_base_url" value="{{$project->doc_base_url}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project API EndPoints Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="api_endpoints_url" type="text" id="api_endpoints_url" value="{{$project->api_endpoints_url}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Project Dev Url') }}</label><span class="text-danger">*</span>
                            <input class="form-control"  name="dev_url" type="text" id="dev_url" value="{{$project->dev_url}}">
                        </div>

                        <div class="form-group">
                            <label for="example-text-input" class="form-control-label">{{ __('Wireframe Url') }}</label><span class="text-danger"> (if any) </span>
                            <input class="form-control"  name="wireframe_url" type="text" id="title" value="{{$project->wireframe_url}}">
                        </div>

<!--                        <div class="form-group">-->
<!--                            <label for="example-date-input" class="form-control-label">{{ __('Date') }}</label>-->
<!--                            <input class="form-control" name="date" type="date" value="{{$project->created_at}}" id="date">-->
<!--                        </div>-->


                            <input type="hidden" name="id" value="">

                        <button type="submit" class="btn bg-gradient-secondary">{{ __('Update') }}</button>
                        <button type="button" class="btn bg-gradient-primary">{{ __('Close') }}</button>
                    </form>

                </div>

            </div>
        </div>




            <div class="col-md-7">
                <div class="card">
                    <div class="card-header p-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h6 class="mb-0">{{ __('Project list') }}</h6>
                            </div>

                        </div>
                        <hr class="horizontal dark mb-0">
                    </div>
                    <div class="card-body p-3 pt-0">
                        <ul class="list-group list-group-flush" data-toggle="checklist">
                            @foreach($projects as $project)
                                <li class="list-group-item border-0 flex-column align-items-start ps-0 py-0 mb-3">
                                    <div class="checklist-item checklist-item-primary ps-2 ms-3">
                                        <div class="d-flex align-items-center">


                                            <div class="form-check">
                                                <input class="form-check-input todo_checkbox" type="checkbox"
                                                       data-id=""
                                                >

                                            </div>
                                            <h6 class="mb-0 text-dark font-weight-bold text-sm">{{$project->name}}</h6>
                                            <div class="dropdown float-lg-end ms-auto pe-4">
                                                <a href="javascript:;" class="cursor-pointer" id="dropdownTable2" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="#"><i class="far fa-trash-alt me-2"></i>Delete</a>
                                                    <a class="btn btn-link text-dark px-3 mb-0" href="#"><i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Edit</a>
                                                </a>

                                            </div>
                                        </div>
                                        <div class="d-flex align-items-center ms-4 mt-3 ps-1">
                                            <div>
                                                <p class="text-xs mb-0 text-secondary font-weight-bold">Date</p>
                                                <span class="text-xs font-weight-bolder"></span>
                                            </div>

                                        </div>
                                    </div>
                                    <hr class="horizontal dark mt-4 mb-0">
                                </li>
                            @endforeach

                        </ul>
                    </div>
                </div>

            </div>
    </div>


@endsection


@section('script')


    <script>
        "use strict";
        $(function () {


            flatpickr("#date", {

                dateFormat: "Y-m-d",
            });

        });




    </script>

    <script>
        tinymce.init({
            selector: '#description',


            plugins: 'table,code',


        });
    </script>
    <script>
        $(function () {
            $('.todo_checkbox').on('change',function () {
                let that = $(this);
                if(this.checked)
                {
                   $.post('/todos/change-status',{
                       id: that.attr('data-id'),
                       status: 'Completed',
                       _token: '{{csrf_token()}}',
                   });
                }
                else{
                    $.post('/todos/change-status',{
                        id: that.attr('data-id'),
                        status: 'Not Completed',
                        _token: '{{csrf_token()}}',
                    });
                }
            });
        });
    </script>


@endsection

resources/views/index.blade.php
@extends('layouts.primary')
@section('content')

@section('head')
    <style>
        .chip{
            width: auto;
            color: black;
            background-color: white;
            border-radius: 7px;
            margin-right: 5px;
            margin-top: 5px;
        }
    </style>
@endsection


<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h6 class="mb-2">
                        {{__('ALL PROJECTS')}}
                    </h6>
                    <span>
                    </span>

                    <div class="page-header mb-4 border-radius-xl">
                        <span class="mask bg-gradient-dark"></span>
                        <div class="container">
                            <div class="row">

                                <div class="col-lg-6 my-auto">
                                    <h5 class="text-white fadeIn2 fadeInBottom mt-4">
                                        {{__($quote->text)}}
                                    </h5>
                                    <p class="text-white opacity-8 fadeIn3 fadeInBottom">{{__($quote->author)}} </p>
                                </div>
                            </div>

                            @if(Auth::user()->admin)
                                     <a  href="{{route('add-project')}}" type="button" class="btn bg-gradient-dark mt-4">{{__('Add New Project')}}</a>
                            @endif

                        </div>
                    </div>

                </div>

                <div class="card-body ">

                    <div class="row">

                        @if(sizeof($projects) < 1)
                            <h4 class="h4 text-center">NO PROJECT CREATED OR ASSIGNED YET!</h4>
                        @endif

                        @foreach($projects as $project)
                            <div class="col-lg-4 col-md-6 col-12 mt-4 mt-lg-0 mb-4">
                            <div class="card text-center">
                                <div class="overflow-hidden bg-gradient-secondary  position-relative border-radius-lg bg-cover p-3">
                                    <span class=" bg-gradient-light opacity-6"></span>
                                    <div class="card-body position-relative z-index-1 d-flex flex-column mt-5">
                                        <h4 class="text-white">{{__('Project')}}</h4>
                                        <h4 class="text-white">{{__($project->name)}}</h4>
                                        <a class="text-white text-sm font-weight-bold mb-0 icon-move-right mt-4" href="#">
                                            {{__('Read More')}}
                                            <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
                                        </a>
                                        <div class="mt-4">
                                            <a href="{{route('project-detail',$project->id)}}" type="button" class="btn btn-outline-light">
                                                {{__('Open')}}

                                            </a>
                                            <a href="#" type="button" class="btn btn-light" onclick="handleCopyTextFromParagraph('{{$project->repository_url}}')">{{__('Clone')}}</a>

                                            @if(Auth::user()->admin)
                                                <a href="{{route('edit-project', $project->id)}}" type="button" class="btn btn-light" >{{__('Edit')}}</a>
                                            @endif

                                            <a href="{{route('modules.index',['project_id' => $project->id])}}" type="button" class="btn btn-light" >{{__('Modules')}}</a>

                                            @if(Auth::user()->admin)
                                            <a href="{{route('staff.index',['project_id' => $project->id,"action" => "assign"])}}" type="button" class="btn btn-light" >{{__('Assign To Resource')}}</a>
                                            @endif

                                            <h5 class="copied" style="display: none">
                                                {{$project->repository_url}}
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

@endsection

@section("script")

<script>
    function handleCopyTextFromParagraph(text) {
        const cb = navigator.clipboard;
        const paragraph = document.querySelector('h5');
        cb.writeText(text);
    }
</script>
@endsection