routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FileUploadController;
use App\Http\Controllers\IframeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Models\Quote;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $settings = [];
    return view('index',compact("settings"));
});

Route::get("/viewer",[IframeController::class, "view"])->name("viewer");

Route::get('/', [AuthController::class,'login']);

Route::get('/profile', [ProfileController::class,'profile']);

Route::post('/profile', [ProfileController::class,'profilePost']);

Route::get('/new-user', [ProfileController::class,'newUser']);

Route::get('/staff', [ProfileController::class,'staff'])->name("staff.index");

//Route::get('/staff/{project_id}', [ProfileController::class,'staff'])->name("assign-project");

Route::post('/user-post', [ProfileController::class,'userPost']);

Route::post('/user-change-password', [ProfileController::class,'userChangePasswordPost']);

Route::get('/login', [AuthController::class,'login'])->name('login');
Route::get('/signup', [AuthController::class,'signup']);
Route::get('/forgot-password', [AuthController::class,'forgotPassword']);
Route::get('/password-reset', [AuthController::class,'passwordReset']);

Route::get('/logout', [AuthController::class,'logout']);

Route::post('/login', [AuthController::class,'loginPost']);

Route::get('/dashboard', [DashboardController::class,'dashboard']);

Route::get('/add-project', [ProjectController::class,'addProject'])->name("add-project");

Route::post('/store-project', [ProjectController::class,'storeProject'])->name("store-project");

Route::get('/project-detail/{id}', [ProjectController::class,'projectDetails'])->name("project-detail");

Route::get('/project/{id}', [DashboardController::class,'editProject'])->name("edit-project");

Route::post('/update-project/{id}', [DashboardController::class,'updateProject'])->name("update-project");

//Route::post('/upload-image', [ImageController::class, 'dropZone' ])->name('drag-drop');

Route::resource('/modules', ModuleController::class);

Route::get('/modules/documentation/{module_id}', [ModuleController::class, "moduleDocumentation"])->name("module-documentation");

Route::resource("/jobs", JobController::class);

Route::get("/jobs-dashboard", [JobController::class,"dashboard"])->name("jobs-dashboard");

//Route::post("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");
Route::get("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");

Route::resource('/tasks', TaskController::class);

Route::get('/document-task/{id}', [TaskController::class,"document"])->name("document-task");

Route::post('/document-task/{id}', [TaskController::class,"documentTask"])->name("task.document");

Route::post('/modules/assign-module', [ModuleController::class, 'assignModule'])->name('assign-module');

Route::get('uploads', [FileUploadController::class, 'fileUploads' ])->name('fileUploads');

//Route::get("/")

//Route::post('file-upload', [FileUploadController::class, 'dropzoneFileUpload' ])->name('dropzoneFileUpload');
Route::post('file-upload', [FileUploadController::class, 'uploadZips' ])->name('dropzoneFileUpload');

Route::get('/test', function (){
    return \App\Models\Task::with(['module' => function($module){
        return $module->with("user");
    }])->get();
});

Route::get('/html-assets/{directory}/{page}', function (\Illuminate\Http\Request $request) {
    if (!$request->hasValidSignature()) {
        abort(401);
    }
});

Route::get("/store-quotes", function(){
     $response = Http::get("https://type.fit/api/quotes");
//     return $response->collect();
     foreach ($response->collect() as $res){
         Quote::create([
             "text" => $res['text'],
             "author" => $res['author'],
         ]);
     }
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Task
 *
 * @property int $id
 * @property string $name
 * @property int $module_id
 * @property string|null $start_date
 * @property string|null $end_date
 * @property string $status
 * @property string|null $description
 * @property string|null $summary
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Task newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Task newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Task query()
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereEndDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereModuleId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereStartDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereSummary($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property int $points
 * @method static \Illuminate\Database\Eloquent\Builder|Task wherePoints($value)
 */
class Task extends Model
{
    use HasFactory;

    protected $guarded = [];


    public function module(){
        return $this->belongsTo(Module::class, 'module_id');
    }

    public function userTask(){
        return $this->hasOne(UserTask::class, "task_id");
    }

    public static function PointsPercentage($module_id){
        $completed_task_points = Task::whereModuleId($module_id)->whereStatus("Finished")->sum("points");
        $moduleTotalPoints = Task::whereModuleId($module_id)->sum("points");
        if ($moduleTotalPoints == 0) return 0;
        return ($completed_task_points/$moduleTotalPoints)* 100;
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;
use App\Models\Task;
use App\Models\UserTask;
use App\Notifications\TaskStatusNotification;
use Illuminate\Http\Request;

class TaskController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $create_url = '/tasks/create';
        if (\request()->has('module_id')){
            $tasks = Task::whereModuleId(\request()->query('module_id'))->get();
            $create_url = route('tasks.create',["module_id" => \request()->query("module_id")]);
        }else{
            $tasks = Task::all();
        }

        return view('tasks.index',[
            'tasks' => $tasks,
            "create_url" => $create_url
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $module_id = \request()->query('module_id');
        $modules = Module::all();

        return view('tasks.create',[
            'modules' => $modules,
            'module_id' => $module_id
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
//        return $request->all();
        $request->validate([
            'name'=>'required|max:150',
            'description' => 'required',
            'points' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'
        ]);

        Task::create($request->except("exit"));

        if ($request->has("exit"))
            return redirect()->route('tasks.index')->with("success","Successfully added a task!");;
        return redirect()->route('tasks.create')->with("success","Successfully added a task!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $status = $request->status;
        $taskObject  = Task::find($id);
        $update = $taskObject->update(["status" => $status]);

        if ($status == "Finished"){
            $user = \Auth::user();
            $user->notify((new TaskStatusNotification($user, $taskObject))->locale('en_US'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function document($id){

        $documentation = UserTask::whereTaskId($id)->whereUserId($this->user->id)->selectRaw("documentation")->first();

        return view("tasks.document",[
            "task_id" => $id,
            "documentation" => $documentation ? $documentation->documentation : ""
            ]);
    }

    public function documentTask(Request $request){
        $request->validate([
//            "documentation" => "required"
        ]);

        $userTask = UserTask::whereTaskId($request->id)->whereUserId($this->user->id)->first();

        if ($userTask){
            $userTask->update([
                "documentation" => $request->documentation
            ]);
        }else {

            UserTask::create([
                "user_id" => $this->user->id,
                "task_id" => $request->id,
                "documentation" => $request->documentation
            ]);
        }

        return redirect()->back()->with("success", "Successfully documented!");
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.primary')


@section('content')

    <div class="card">
        <div class="card-header">
            {{__('Add Task to Module')}}
        </div>

        <div class="card-body">
            <form action="{{route('tasks.store')}}" method="post">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="list-unstyled">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label for="example-text-input" class="form-control-label">
                        {{__('Name')}}

                    </label><span class="text-danger">*</span>
                    <input class="form-control" name="name" type="text" id="example-text-input">
                </div>

                <div class="form-group">
                        <label for="example-text-input" class="form-control-label">
                            {{__('Summary')}}

                        </label><span class="text-danger">*</span>
                        <input class="form-control" name="summary" type="text" id="example-text-input">
                </div>

                <div class="form-group">
                        <label for="module_id" class="form-control-label">
                            {{__('Module')}}

                        </label><span class="text-danger">*</span>

                        <select class="form-select" name="module_id">
                            <option value="">Choose Module</option>
                           @foreach ($modules as $module)
                                <option @if ($module_id == $module->id) selected @endif value="{{$module->id}}">{{$module->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="row">

                            <div class="col-md-6">
                                <label for="points" class="form-control-label">
                                    {{__('Allocate Points')}}

                                </label><span class="text-danger">*</span>
                                <input type="number" name="points" placeholder="Points for this task" id="points" class="form-control" />
                            </div>

                        </div>

                    </div>


                <div class="mb-3">
                        <label for="description">{{__('Description')}}</label><span class="text-danger">*</span>
                        <textarea class="form-control" name="description" id="description" rows="3"></textarea>
                </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="start_date" class="form-control-label">{{__('Start Date')}}</label>
                                <input class="form-control" type="date" name="start_date" id="date">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="end_date" class="form-control-label">{{__('End Date')}}</label>
                                <input class="form-control" type="date" name="end_date" id="date">
                            </div>
                        </div>
                    </div>

                @csrf

                    <button type="submit" class="btn bg-gradient-faded-success">
                        {{__('Save and Continue')}}
                    </button>

                <button type="submit" name="exit"  value="exit" class="btn bg-gradient-secondary">
                    {{__('Save and Exit')}}
                </button>

{{--                <button type="button" class="btn bg-gradient-primary">--}}
{{--                    {{__('Close')}}--}}
{{--                </button>--}}
            </form>

        </div>

    </div>

@endsection
@section('script')

    <script>
        "use strict";
        $(function () {


            flatpickr("#date", {

                dateFormat: "Y-m-d",
            });

        });


    </script>
    <script>
        tinymce.init({
            selector: '#description',

            plugins: 'table,code',


        });
    </script>


@endsection

resources/views/tasks/document.blade.php
@php

@endphp

@extends('layouts.primary')


@section('content')

    <div class="card">
        <div class="card-header">
            {{__('Add Documentation to Task')}}
        </div>

        <div class="card-body">
            <form action="{{route('task.document',$task_id)}}" method="post">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="list-unstyled">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <div class="mb-3">
                        <label for="description">{{__('Document Task')}}</label><span class="text-danger">*</span>
                        <textarea class="form-control" name="documentation" id="description" rows="20">
                            {{ $documentation }}
                        </textarea>
                </div>

                    <input type="hidden" name="id" value="{{$task_id}}">

                @csrf

                    <button type="submit" class="btn bg-gradient-faded-success">
                        {{__('Save')}}
                    </button>

                <a href="{{route("tasks.index")}}" type="button" class="btn bg-gradient-primary">
                    {{__('Close')}}
                </a>
            </form>

        </div>

    </div>

@endsection
@section('script')

    <script>
        "use strict";
        $(function () {


            flatpickr("#date", {

                dateFormat: "Y-m-d",
            });

        });


    </script>
    <script>
        tinymce.init({
            selector: '#description',
            plugins: 'table,code,image',


        });
    </script>


@endsection

resources/views/tasks/index.blade.php
@extends('layouts.primary')
@section('content')

@section("head")
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@endsection

    <div class="page-header mb-4 border-radius-xl">
        <span class="mask bg-gradient-dark"></span>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 my-auto">

                    <h5 class="text-white fadeIn2 fadeInBottom mt-4">{{__('“A dream without a plan is just a wish.”')}}
                    </h5>

                </div>
            </div>

            <a href="{{$create_url}}" type="button" class="btn bg-gradient-light">{{__('Add New Task')}}</a>

        </div>
    </div>

    <div class="row">

        <div class="col-md-12 mt-4">
            <div class="card">

                <div class="card mt-4">
                    <div class="card-header pb-0 p-3">
                        <div class="d-flex align-items-center">
                            <h6 class="mb-0">{{__('Recent Tasks')}}</h6>

                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    {{__('Task Name')}}
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                    {{__('Task Summary')}}
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">
                                    {{__('Task Points')}}
                                </th>

                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">{{__('Dates')}}</th>


                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">{{__('Action')}}</th>

                            </tr>
                            </thead>
                            <tbody>

                            @foreach($tasks as $project)
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1 text-center">
                                            <div class="avatar avatar-sm me-3 bg-gradient-dark border-radius-md p-2">
                                                <h6 class="text-white">{{$project->name['0']}}</h6>
                                            </div>
                                            <div class="d-flex flex-column justify-content-center text-center">
                                                <h6 class="mb-0 text-xs">{{$project->name}}</h6>
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        <div class="d-flex px-2 py-1 text-center">

                                            <div class="d-flex flex-column justify-content-center text-center">
                                                <h6 class="mb-0 text-xs">{{$project->summary}}</h6>
                                            </div>
                                        </div>
                                    </td>

                                    <td class="align-left text-center text-sm">
                                        <span class="badge bg-gradient-success font-weight-bold ">{{$project->points}}</span>
                                    </td>

{{--                                    <td class="align-middle text-center text-sm">--}}
{{--                                        <span class="badge bg-gradient-success font-weight-bold ">{{$project->start_date}}</span>--}}
{{--                                    </td>--}}

                                    <td class="align-middle text-center text-sm">
                                        <span class="badge bg-gradient-success font-weight-bold ">{{$project->start_date}}</span>
                                        <br>
                                        <span class="badge bg-gradient-primary font-weight-bold">{{$project->end_date}}</span>
                                    </td>


                                    <td class="align-middle text-center text-sm">

                                        <div class="btn-group">
                                            <button type="button" class="btn btn-dark">{{$project->status}}</button>
                                            <button type="button" class="btn btn-outline-dark dropdown-toggle dropdown-toggle-split"
                                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <div class="dropdown-menu bg-outline-dark" >
                                                @php $task_id = $project->id; @endphp
                                                <a class="dropdown-item" onclick="changeStatus('Pending',{{$task_id}})">Pending</a>
                                                <a class="dropdown-item"  onclick="changeStatus('Started',{{$task_id}})">Started</a>
                                                <a class="dropdown-item"  onclick="changeStatus('Finished', {{$task_id}})">Finished</a>
                                            </div>
                                        </div>

                                        <br>
                                        <a href="{{route("document-task",$task_id)}}" class="btn btn-dark">DOCUMENT TASK</a>
                                    </td>
                                </tr>

                            @endforeach

                            </tbody>
                        </table>
                    </div>

                </div>

            </div>

    </div>

@endsection

@section("script")

    <script>
         function changeStatus(status,id){
            fetch(`/tasks/${id}`, {
                method: 'PUT',
                headers: {
                    'Accept': 'application/json, text/plain, */*',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({status: status})
            }).then(function(){
                location.reload();
            });

            console.log(content);
        }
    </script>


@endsection