routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FileUploadController;
use App\Http\Controllers\IframeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Models\Quote;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $settings = [];
    return view('index',compact("settings"));
});

Route::get("/viewer",[IframeController::class, "view"])->name("viewer");

Route::get('/', [AuthController::class,'login']);

Route::get('/profile', [ProfileController::class,'profile']);

Route::post('/profile', [ProfileController::class,'profilePost']);

Route::get('/new-user', [ProfileController::class,'newUser']);

Route::get('/staff', [ProfileController::class,'staff'])->name("staff.index");

//Route::get('/staff/{project_id}', [ProfileController::class,'staff'])->name("assign-project");

Route::post('/user-post', [ProfileController::class,'userPost']);

Route::post('/user-change-password', [ProfileController::class,'userChangePasswordPost']);

Route::get('/login', [AuthController::class,'login'])->name('login');
Route::get('/signup', [AuthController::class,'signup']);
Route::get('/forgot-password', [AuthController::class,'forgotPassword']);
Route::get('/password-reset', [AuthController::class,'passwordReset']);

Route::get('/logout', [AuthController::class,'logout']);

Route::post('/login', [AuthController::class,'loginPost']);

Route::get('/dashboard', [DashboardController::class,'dashboard']);

Route::get('/add-project', [ProjectController::class,'addProject'])->name("add-project");

Route::post('/store-project', [ProjectController::class,'storeProject'])->name("store-project");

Route::get('/project-detail/{id}', [ProjectController::class,'projectDetails'])->name("project-detail");

Route::get('/project/{id}', [DashboardController::class,'editProject'])->name("edit-project");

Route::post('/update-project/{id}', [DashboardController::class,'updateProject'])->name("update-project");

//Route::post('/upload-image', [ImageController::class, 'dropZone' ])->name('drag-drop');

Route::resource('/modules', ModuleController::class);

Route::get('/modules/documentation/{module_id}', [ModuleController::class, "moduleDocumentation"])->name("module-documentation");

Route::resource("/jobs", JobController::class);

Route::get("/jobs-dashboard", [JobController::class,"dashboard"])->name("jobs-dashboard");

//Route::post("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");
Route::get("/take-gig/{module_id}", [JobController::class,"takeGig"])->name("take-gig");

Route::resource('/tasks', TaskController::class);

Route::get('/document-task/{id}', [TaskController::class,"document"])->name("document-task");

Route::post('/document-task/{id}', [TaskController::class,"documentTask"])->name("task.document");

Route::post('/modules/assign-module', [ModuleController::class, 'assignModule'])->name('assign-module');

Route::get('uploads', [FileUploadController::class, 'fileUploads' ])->name('fileUploads');

//Route::get("/")

//Route::post('file-upload', [FileUploadController::class, 'dropzoneFileUpload' ])->name('dropzoneFileUpload');
Route::post('file-upload', [FileUploadController::class, 'uploadZips' ])->name('dropzoneFileUpload');

Route::get('/test', function (){
    return \App\Models\Task::with(['module' => function($module){
        return $module->with("user");
    }])->get();
});

Route::get('/html-assets/{directory}/{page}', function (\Illuminate\Http\Request $request) {
    if (!$request->hasValidSignature()) {
        abort(401);
    }
});

Route::get("/store-quotes", function(){
     $response = Http::get("https://type.fit/api/quotes");
//     return $response->collect();
     foreach ($response->collect() as $res){
         Quote::create([
             "text" => $res['text'],
             "author" => $res['author'],
         ]);
     }
});

app/Models/Module.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Module
 *
 * @property int $id
 * @property string $name
 * @property int $project_id
 * @property string|null $start_date
 * @property string|null $end_date
 * @property string $status
 * @property string|null $description
 * @property string|null $summary
 * @property int $category_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ModuleSkill[] $skills
 * @property-read int|null $skills_count
 * @method static \Illuminate\Database\Eloquent\Builder|Module newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Module newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Module query()
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereEndDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereProjectId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereStartDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereSummary($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Module whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Module extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = "modules";

    public function skills(){
        return $this->hasMany(ModuleSkill::class,"module_id");
    }

    public function user(){
        return $this->hasOne(UserModule::class,"module_id");
    }

    public function project(){
        return $this->belongsTo(Project::class);
    }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Module;
use App\Models\ModuleSkill;
use App\Models\Project;
use App\Models\Task;
use App\Models\User;
use App\Models\UserModule;
use App\Notifications\AssignModuleNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ModuleController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $project_id = \request()->query('project_id');
        $staff_id   = \request()->query('staff');
        $create_url = "/modules/create";

        if (\request()->has('project_id')) {
            $modules = Module::with(["skills" => function($skills){
                return $skills->with("skill")->get();
            }])->whereProjectId($project_id)->get();
            $create_url = route('modules.create',["project_id" => $project_id]);
        }

        else{
             $modules = Module::with(["skills" => function($skills){
                return $skills->with("skill:id,name")->get();
            }])->get();
        }

        if (\request()->has('staff')) {
            if (\request()->has("page") and \request()->query("page") == "projects") {
                if (Auth::user()->admin) {
                    $modules = Module::with(["skills" => function ($skills) {
                        return $skills->with("skill:id,name")->get();
                    }]);
                } else {
                    $userModuleIds = UserModule::whereUserId($staff_id)->pluck("module_id");
                    $modules = Module::with(["skills" => function ($skills) {
                        return $skills->with("skill:id,name")->get();
                    }])->whereIn("id", $userModuleIds)->get();
                };
            }
            $create_url = route('modules.create',["staff" => $staff_id]);
        }

        return view('modules.index', [
            "modules" => $modules,
            "settings" => [],
            "create_url" => $create_url,
            "project_id" => $project_id
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $project = false;
        $project_id = \request()->query('project_id');

        if($request->id)
        {
            $project = Module::find($request->id);
        }

        $selectProjects = Project::all();
        $categories     = Category::all();

        return \view('modules.create',[

            'selected_navigation' => 'projects',
            'project'=> $project,
            'selectProjects' => $selectProjects,
            'categories' => $categories,
            'settings' => [],
            'project_id' => $project_id
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:150',
            'description' => 'required',
            'id'=>'nullable|integer',
            'start_date' => 'required',
            'end_date' => 'required',
            'project_id' => 'required',
            'category_id' => 'required',
            'skills'   =>  'required'
        ]);

        $module = false;

        if($request->id){
            $module = Module::find($request->id);
        }

        if(!$module ){
              $module  = new Module();
        }

        $module->name = $request->name;
        $module->project_id = $request->project_id;
        $module->category_id = $request->category_id;
        $module->start_date = $request->start_date;
        $module->end_date = $request->end_date;
        $module->summary = $request->summary;
        $module->description = ($request->description);

        $skills = $request->get("skills");

        if($module->save()){
            foreach ($skills as $skill){
                $moduleSkill = new ModuleSkill();
                $moduleSkill->skill_id = $skill;
                $moduleSkill->module_id = $module->id;
                $moduleSkill->save();
            }
        }

        if ($request->has('staff') && !empty($request->staff)){

//            try{
                $user = User::find($request->staff);
                $this->assignModuleUtility($user, $module);

                return redirect()->route('modules.index',[
                    'staff'=> $request->staff
                ])->with("success", "Successfully added a module!");
//            }catch (\Exception $exception){
//                throw New \Exception("Problem with the action!",500);
//            }

        }

        return redirect()->route('modules.index',[
            'project_id'=> $request->project_id
        ])->with("success","Successfully added a module!");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $module = Module::find($id);
        $selectProjects = Project::all();

        return view('modules.edit',[
            'module' => $module,
            'selectProjects' => $selectProjects,
            'settings' => []
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        Module::find($id)->update($request->all());

        return redirect()->route('modules.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function assignModule(Request $request){
        $user_id = $request->user_id;
        $module_id = $request->module_id;
        $user = User::find($user_id);
        $module = Module::find($module_id);

        if (UserModule::find($module_id)){
            return redirect()->route('modules.index',['staff'=> $user_id])
                ->with("info","This module has already been assigned!");
        }

        $this->assignModuleUtility($user, $module);

        return redirect()->route('modules.index',['staff'=> $user_id]);
    }

    public function moduleDocumentation($id){
        $module = Module::find($id);
        $tasks = Task::with("userTask")->whereModuleId($id)->get();

        return view("modules.documentation",[
            "tasks" => $tasks,
            "module" => $module
        ]);
    }


    private function assignModuleUtility(User $user, Module $module){

        \DB::beginTransaction();
            UserModule::create([
                "user_id" => $user->id,
                "module_id" => $module->id
            ]);
            $user->notify((new AssignModuleNotification($user, $module))->locale('en_US'));
        \DB::commit();
    }
}

resources/views/modules/create.blade.php
@extends('layouts.primary')
@section('content')
    <div class="container-fluid py-4">
        <div class="row">
            <form action="{{route('modules.store')}}" method="post">
                @csrf
                @if ($errors->any())
                    <div class="alert alert-danger" style="color: white;">
                        <ul class="list-unstyled">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="col-lg-9 col-12 mx-auto">
                    <div class="card card-body mt-4">
                        <h6 class="mb-0">{{__('New Module')}}</h6>
                        <p class="text-sm mb-0">{{__('Create new module')}}</p>
                        <hr class="horizontal dark my-3">


                        <label for="projectName" class="form-label">{{__('Module Name')}}</label>
                        <input type="text" value="{{old("name")}}"  name="name" class="form-control" id="projectName">
                        <br>

                        <label for="projectName" class="form-label">{{__('Category')}}</label>
                        <select class="form-control" name="category_id">
                            <option value="">Select Category </option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>

                        <br>
                        <label for="projectName" class="form-label">{{__('Project')}}</label>
                        <select class="form-control" name="project_id">
                            <option value="">Select Project </option>
                            @foreach($selectProjects as $selectProject)
                                <option @if($project_id == $selectProject->id ) selected @endif
                                value="{{$selectProject->id}}">{{$selectProject->name}}</option>
                            @endforeach
                        </select>


                        <label class="mt-4 text-sm mb-0">{{__('Project Summary')}}</label>
                        <p class="form-text text-muted text-xs ms-1">
                            {{__('Write a short summary of the module.Within 225 words')}}
                        </p>

                        <div class="form-group">
                            <textarea name="summary" class="form-control" rows="4" id="editor" name="budget">{{old('summary')}}</textarea>
                        </div>


                        <div class="row mt-4">
                            <div class="col-6">
                                <label class="form-label">{{__('Start Date')}}</label>
                                <input class="form-control datetimepicker" name="start_date" type="date" id="start_date" placeholder="Please select start date"
                                       value="{{old("start_date")}}" />
                            </div>
                            <div class="col-6">
                                <label class="form-label">{{__('End Date')}}</label>
                                <input class="form-control datetimepicker" name="end_date" type="date" id="end_date"  placeholder="Please select end date"
                                 value="{{old('end_date')}}">
                            </div>
                        </div>


                        <label class="mt-4 text-sm mb-0">{{__('Module Description')}}</label>
                        <p class="form-text text-muted text-xs ms-1">
                            {{__('Write a well organised description of the module.')}}
                        </p>

                        <div class="form-group">
                            <textarea class="form-control" rows="10" id="description" name="description">{{old('description')}}
                            </textarea>
                        </div>

                        <div class="row mt-3 mb-4">
                            <div class="col-12">
                                <label class="text-sm mb-0">{{__('Stack Required')}}</label>
                                <select class="select-skills" name="skills[]" multiple="multiple" style="width: 100%; height: 120px"></select>
                                {{--                                                <input  name="skills" class="multisteps-form__input form-control" type="text" @if(!empty($selected_user)) value="{{$selected_user->twitter}}" @endif />--}}
                            </div>

                        </div>

                        <div class="row mt-3 mb-4">
                            <div class="col-12">
                                <label class="text-sm mb-0">{{__('Private')}}</label>
                                <input type="checkbox" name="private" />
{{--                                <select class="select-skills" name="skills[]" multiple="multiple" style="width: 100%; height: 120px"></select>--}}
                                {{--                                                <input  name="skills" class="multisteps-form__input form-control" type="text" @if(!empty($selected_user)) value="{{$selected_user->twitter}}" @endif />--}}
                            </div>

                        </div>

                        <input type="hidden" name="staff" value="{{Request::query("staff")}}" />

                        <div class="d-flex  mt-4">

                            <button type="submit" name="button" class="btn bg-gradient-primary m-0 ">
                                {{__('Save')}}
                            </button>
                        </div>
                    </div>
                </div>

            </form>

        </div>

    </div>
@endsection

@section('script')

    <script>
        "use strict";
        $(function () {


            flatpickr("#start_date", {

                dateFormat: "Y-m-d",
            });

            flatpickr("#end_date", {

                dateFormat: "Y-m-d",
            });


            tinymce.init({
                selector: '#description',


                plugins: 'table,code',


            });

        });


    </script>

    <script>
        $(".select-skills").select2({
            placeholder: 'Type skill name...',
            minimumInputLength: 3,
            theme: "classic",
            allowClear: true,
            ajax: {
                url: '/api/skills',
                dataType: 'json',
                data: function(params) {
                    return {
                        q: params.term
                    }
                },
                processResults: function (data, page) {
                    return {
                        results: data
                    };
                },
                cache: true
            }
        });

    </script>


@endsection

resources/views/modules/documentation.blade.php
@extends("layouts.primary")

@section("content")

<div class="container-fluid py-4">
    <div class="col-lg-9 mx-auto">
        <div class="card card-body ">
            <div class="page-header mb-4 border-radius-xl">
                <span class="mask bg-gradient-dark"></span>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 mt-3 mb-6 text-center my-auto">
                            <h3 class="text-white">
                                {{$module->name}} Documentation
                            </h3>
                            <h2 class="text-white fadeIn2 fadeInBottom mt-4">{{$module->name}}</h2>
                            <h5 class="text-white fadeIn2 fadeInBottom">{{$module->start_date}} - {{$module->end_date}}</h5>
                        </div>
                    </div>
                </div>
            </div>

            @foreach($tasks as $task)

            <div class="text-center mt-4">
                <h6>{{$task->name}}</h6>
            </div>
            <div>
                <p class="pl-5">
                    {!! $task->userTask? $task->userTask->documentation : "" !!}
                </p>
            </div>
            @endforeach

        </div>
    </div>
</div>

@endsection

resources/views/modules/edit.blade.php
@php
    $admin = Auth::user()->admin;
@endphp
@extends('layouts.primary')
@section('content')
    <div class="container-fluid py-4">
        <div class="row">
            <form action="{{route('modules.update',$module->id)}}" method="post">
                @method('PATCH')
                @csrf
                @if ($errors->any())
                    <div class="alert alert-danger" style="color: white;">
                        <ul class="list-unstyled">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="col-lg-9 col-12 mx-auto">
                    <div class="card card-body mt-4">
                        @if(Auth::user()->admin)
                            <h6 class="mb-0">{{__('Edit Module')}}</h6>
                            <p class="text-sm mb-0">{{__('Edit module')}}</p>
                            <hr class="horizontal dark my-3">

                        @else
                            <h6 class="mb-0">{{__('View Module')}}</h6>
                            <p class="text-sm mb-0">{{__(' module')}}</p>
                            <hr class="horizontal dark my-3">
                        @endif


                        <label for="projectName" class="form-label">{{__('Module Name')}}</label>
                        <input type="text" value="{{$module->name}}"  name="name" class="form-control" id="projectName" @if(!$admin) disabled @endif  >
                        <br>

                        <label for="projectName" class="form-label">{{__('Project')}}</label>
                        <select class="form-control" name="project_id" @if(!$admin) disabled @endif>
                            @foreach($selectProjects as $selectProject)
                                <option value="{{$selectProject->id}}">{{$selectProject->name}}</option>
                            @endforeach
                        </select>

                        <label class="mt-4 text-sm mb-0">{{__('Project Summary')}}</label>
                        <p class="form-text text-muted text-xs ms-1">
                            {{__('Write a short summary of the module.Within 225 words')}}
                        </p>

                        <div class="form-group">
                            <textarea name="summary" class="form-control" rows="4" id="editor" name="budget" @if(!$admin) disabled @endif >{{$module->summary}}</textarea>
                        </div>

                        <div class="row mt-4">
                            <div class="col-6">
                                <label class="form-label">{{__('Start Date')}}</label>
                                <input class="form-control datetimepicker" name="start_date" type="date" id="start_date" placeholder="Please select start date"
                                       value="{{$module->start_date}}" @if(!$admin) disabled @endif />
                            </div>
                            <div class="col-6">
                                <label class="form-label">{{__('End Date')}}</label>
                                <input class="form-control datetimepicker" name="end_date" type="date" id="end_date"  placeholder="Please select end date"
                                       value="{{$module->end_date}}" @if(!$admin) disabled @endif >
                            </div>
                        </div>


                        <label class="mt-4 text-sm mb-0">{{__('Module Description')}}</label>
                        <p class="form-text text-muted text-xs ms-1">
                            {{__('Write a well organised description of the module.')}}
                        </p>

                        <div class="form-group">
                            <textarea  class="form-control" rows="10" id="description" name="description" >
                                {{$module->description}}
                            </textarea>
                        </div>

                        <div class="row mt-3 mb-4">
                                <div class="col-12">
                                    <label class="text-sm mb-0">{{__('Private')}}</label>
                                    <input type="checkbox" name="private" @if($module->private) checked @endif />
                                </div>

                            </div>

                        @if($admin)
                            <div class="d-flex  mt-4">

                                <button type="submit" class="btn bg-gradient-primary m-0 ">
                                    {{__('UPDATE')}}
                                </button>

                            </div>
                        @endif

                    </div>
                </div>

            </form>

        </div>

    </div>
@endsection

@section('script')

    <script>

        let status = "{{$admin}}" == 1 ? 0 : 1;
        "use strict";
        $(function () {


            flatpickr("#start_date", {

                dateFormat: "Y-m-d",
            });

            flatpickr("#end_date", {

                dateFormat: "Y-m-d",
            });


            tinymce.init({
                selector: '#description',
                plugins: 'table,code',
                readonly: status

            });

        });


    </script>

@endsection